import * as THREE from 'three';
import { Component } from 'zortengine';

/**
 * Intelligent NPCs following paths generated by A* Navigation System.
 */
export class SidewalkNpcController extends Component {
    constructor(options = {}) {
        super();
        this.navSystem = options.navSystem;
        this.body = options.body;
        this.bounds = options.bounds;
        this.playersBase = options.players; // Array of players
        this.rng = options.rng;
        this.moveSpeed = options.moveSpeed ?? (2.4 + Math.random() * 0.8);
        this.peerNpcs = null;
        
        this.targetBase = new THREE.Vector3();
        this.path = [];
        this.pathIndex = 0;
        
        this.stuckTimer = 0;
        this.lastPos = new THREE.Vector3();
        
        this._pickNewDestination();
    }

    _pickNewDestination() {
        const { xMin, xMax, zMin, zMax } = this.bounds;
        const maxTry = 20;

        for (let t = 0; t < maxTry; t++) {
            const tx = xMin + Math.random() * (xMax - xMin);
            const tz = zMin + Math.random() * (zMax - zMin);
            const goal = new THREE.Vector3(tx, 0, tz);

            const foundPath = this.navSystem.findPath(this.body.position, goal);
            if (foundPath && foundPath.length > 1) {
                this.path = foundPath;
                this.pathIndex = 1; // 0 is start point
                this.targetBase.copy(goal);
                return;
            }
        }

        // Fallback: stay put for a while
        this.path = [];
    }

    update(delta = 1 / 60) {
        const owner = this.owner;
        if (!owner || !this.body) return;

        const pos = owner.group.position;
        const moveDist = pos.distanceTo(this.lastPos);
        this.lastPos.copy(pos);

        // 1. Stuck Detection
        if (moveDist < 0.012) {
            this.stuckTimer += delta;
            if (this.stuckTimer > 2.0) {
                this._pickNewDestination();
                this.stuckTimer = 0;
                this.body.position.x += (Math.random() - 0.5) * 0.3;
            }
        } else {
            this.stuckTimer = 0;
        }

        // 2. Path Following
        if (this.path.length === 0 || this.pathIndex >= this.path.length) {
            if (Math.random() < 0.02) this._pickNewDestination();
            this.body.velocity.scale(0.8, this.body.velocity);
            if (owner.fsm) owner.fsm.setState('idle');
            return;
        }

        const wayPoint = this.path[this.pathIndex];
        const toWayPoint = new THREE.Vector3().subVectors(wayPoint, pos);
        toWayPoint.y = 0;
        const dist = toWayPoint.length();

        if (dist < 0.6) {
            this.pathIndex++;
            return;
        }

        toWayPoint.normalize();
        let vx = toWayPoint.x * this.moveSpeed;
        let vz = toWayPoint.z * this.moveSpeed;

        // 3. Dynamic Avoidance (Peers and Players)
        let sx = 0, sz = 0;

        // Peer Avoidance
        const peers = this.peerNpcs;
        if (peers?.length) {
            for (const other of peers) {
                if (!other?.body || other === owner) continue;
                const dx = pos.x - other.body.position.x;
                const dz = pos.z - other.body.position.z;
                const d2 = dx * dx + dz * dz;
                if (d2 < 2.0) {
                    const idist = Math.sqrt(d2);
                    const push = (1 - idist / 1.5) * 4.0;
                    sx += (dx / idist) * push;
                    sz += (dz / idist) * push;
                }
            }
        }

        // Player Avoidance
        if (this.playersBase?.length) {
            for (const player of this.playersBase) {
                if (!player?.group) continue;
                const dx = pos.x - player.group.position.x;
                const dz = pos.z - player.group.position.z;
                const d2 = dx * dx + dz * dz;
                if (d2 < 9.0) { // Larger avoidance radius for player
                    const idist = Math.sqrt(d2);
                    const sep = 2.4;
                    if (idist < sep) {
                        const push = (1 - idist / sep) * 7.5;
                        sx += (dx / idist) * push;
                        sz += (dz / idist) * push;
                    }
                }
            }
        }

        vx += sx;
        vz += sz;

        this.body.velocity.x = vx;
        this.body.velocity.z = vz;

        if (Math.abs(vx) > 0.1 || Math.abs(vz) > 0.1) {
            owner.group.rotation.y = Math.atan2(vx, vz);
        }
        if (owner.fsm) owner.fsm.setState('walk');
    }
}
